pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'dotnet test $(buildConfiguration)'

- script: dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'dotnet pack $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'BuildArtifacts'